[licenses]
allow-osi-fsf-free = "neither"
copyleft = "warn"
default = "warn"
unlicensed = "allow"
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "Artistic-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MIT-0",
    "0BSD",
    "Unicode-DFS-2016",
    "Unlicense",
    "Zlib",
]
[licenses.private]
ignore = true

