on:
  push:
    branch:
      - main

jobs:
  publish-private-create:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/publish-rust-crate.yml@v1.0.0
    with:
      private-registry-host: https://github.com/rust-lang/crates.io.git
      private-registry-name: public
      private-registry-http: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      private-registry-token: ${{ secrets.CARGO_PUBLIC_REGISTRY_TOKEN }}
      discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
