on:
  push:
    branch:
      - main

jobs:
  publish-private-create:
    uses: ForesightMiningSoftwareCorporation/github/.github/workflows/publish-rust-crate.yml@v1.0.0
    with:
      public-registry: true
      required_packages: libasound2-dev
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      public-registry-token: ${{ secrets.CARGO_PUBLIC_REGISTRY_TOKEN }}
      discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
      approval_app_id: ${{ secrets.ACTIONS_APPROVERS_APP_ID }}
      approval_app_private_key: ${{ secrets.ACTIONS_APPROVERS_APP_PRIVATE_KEY }}
